# Generated by Django 5.0 on 2023-12-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('asuLevel', models.IntegerField()),
                ('cellId', models.CharField(max_length=255)),
                ('channelBands', models.CharField(max_length=255)),
                ('channelBandwidth', models.BigIntegerField()),
                ('channelQuality', models.IntegerField()),
                ('gpsUpdateTime', models.BigIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('networkId', models.BigIntegerField()),
                ('networkType', models.CharField(max_length=100)),
                ('networkUpdateTime', models.BigIntegerField()),
                ('operatorName', models.CharField(max_length=100)),
                ('signalStrength', models.IntegerField()),
                ('cellId_PCI', models.CharField(max_length=255)),
                ('cellId_TAC', models.CharField(max_length=255)),
            ],
        ),
    ]
