# Generated by Django 5.0 on 2023-12-30 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0002_networkdata_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpolatedNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=100)),
                ('coordinates', models.TextField()),
                ('data_selection', models.CharField(max_length=50)),
                ('interpolation_technique', models.CharField(max_length=50)),
                ('combined_data', models.JSONField()),
                ('metrics', models.JSONField()),
                ('summary_metrics', models.JSONField(blank=True, null=True)),
                ('OD_metrics', models.JSONField(blank=True, null=True)),
                ('area', models.FloatField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
