# Generated by Django 5.0 on 2023-12-30 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0003_interpolatednetwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interpolatednetwork',
            old_name='combined_data',
            new_name='interpolated_data',
        ),
        migrations.RemoveField(
            model_name='interpolatednetwork',
            name='OD_metrics',
        ),
    ]
